version: '3'
services:
  benchmark:
    restart: always
    container_name: products_benchmark
    env_file:
      - ./env/.env.benchmark
    volumes:
      - ./input:/app/input/
      - ./output:/app/output/
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: 'node index.js'
    networks:
      - app-network

networks:
  app-network:
    external: true
