version: '3'
services:
  benchmark:
    restart: always
    container_name: products_benchmark
    environment:
      - BY_PRODUCTS_ONLY=1
    volumes:
      - ./input:/app/input/
      - ./output:/app/output/
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: 'node index.js'
    networks:
      - app-network

networks:
  app-network:
    external: true
